// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feuxtstvjnsysirosxnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZldXh0c3R2am5zeXNpcm9zeG51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMjQ4MzAsImV4cCI6MjA1NTcwMDgzMH0.2mt3iNZ8og_ATWlNHKI_6siS2K_aRceay55kWswJP9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);